#
# ███████╗██╗░░██╗██╗░░░░░███████╗██████╗░
# ██╔════╝╚██╗██╔╝██║░░░░░██╔════╝██╔══██╗
# █████╗░░░╚███╔╝░██║░░░░░█████╗░░██████╔╝
# ██╔══╝░░░██╔██╗░██║░░░░░██╔══╝░░██╔══██╗
# ███████╗██╔╝╚██╗███████╗███████╗██║░░██║
# ╚══════╝╚═╝░░╚═╝╚══════╝╚══════╝╚═╝░░╚═╝
# Kira Development plugin Loader - https://discord.gg/PeXupemGyS
#

LICENSE: 'XXXX-XXXX-XXXX-XXXX' # Put your license here
Products: [] # Capitalized letters are important