#
#███████╗██╗░░██╗██╗░░░░░███████╗██████╗░
#██╔════╝╚██╗██╔╝██║░░░░░██╔════╝██╔══██╗
#█████╗░░░╚███╔╝░██║░░░░░█████╗░░██████╔╝
#██╔══╝░░░██╔██╗░██║░░░░░██╔══╝░░██╔══██╗
#███████╗██╔╝╚██╗███████╗███████╗██║░░██║
#╚══════╝╚═╝░░╚═╝╚══════╝╚══════╝╚═╝░░╚═╝
# Kira Development plugin Loader - https://kiradev.xyz

LICENSE: 'XXXX-XXXX-XXXX-XXXX' # Put your license here
Products: []
